// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement;

import javax.vecmath.Color3f;
import javax.vecmath.Point3d;

import java.util.ArrayList;
import javax.vecmath.Vector3d;

import RootElement.Robot;
import simbad.sim.RobotFactory;

/************************************************************/
/**
 * 
 */
public class Rescuer extends Robot {
	
	private ArrayList<Point3d> victimPos = new ArrayList<Point3d>();

	
	//constructor
	public Rescuer(Vector3d position, String name, Color3f color) {
		super(position, name);
		this.setColor(color);
		this.setMode("rescue");
        this.bumpers = RobotFactory.addBumperBeltSensor(this, 16);
        this.sonars = RobotFactory.addSonarBeltSensor(this, 8);
        this.lamp = RobotFactory.addLamp(this);
    	
	}
	
	@Override
	public void setLocations(ArrayList<Point3d> copy){
		
		victimPos = (ArrayList<Point3d>)copy.clone();
		System.out.println(victimPos.toString());
	}

	@Override
	public void initBehavior() {
		System.out.println("I exist but is not my turn [" + this.name + "]");
		this.detach();
	}

	public void goAround(){
//		this.getCoords(myPos);
		rotateY(15);
	}
	
	public void obstacleDetected(){
		double leftSonar = sonars.getMeasurement(4);
		double rightSonar = sonars.getMeasurement(2);
		
		if((sonars.getFrontQuadrantHits() > 0) || rightSonar < 0.3 || leftSonar < 0.3){
			setMode("avoid");
		} else {
			setMode("rescue");
		}
	}

	@Override
	public void performBehavior() { 

		
	}
};
